name: worldtime
version: '1.0.1'
summary: WorldTime is a console based tool to display local times around the world
description: |
  WorldTime is a small utility that will display local time in cities
  around the world.  The user can define a custom set of cities to show

grade: stable
confinement: strict
base: core18

# Enable faster LZO compression
compression: lzo

apps:
  worldtime:
    command: bin/java -Djava.util.prefs.userRoot="$SNAP_USER_DATA" -jar $SNAP/jar/worldtime.jar

parts:
  library:
    plugin: maven
    source: https://github.com/frossm/library.git
    source-type: git
    source-tag: 'v2021.10.24'
    maven-options: [install]

  worldtime:
    plugin: maven
    source: https://github.com/frossm/worldtime.git
    source-branch: master
    source-type: git
    after: [library]

plugs:
   rpncalc-network:
      interface: network